name: Bake Server Image

on:
  workflow_dispatch:
#  push:
#    branches: [ "main" ]
#    paths:
#     - ".github/workflows/bake-image.yml"
#     - "packer/**"

jobs:
  bake:
#    runs-on: ubuntu-latest
    runs-on: [self-hosted, linux, x64, server-bake]
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            qemu-system-x86 \
            qemu-utils \
            unzip \
            curl
    
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            qemu-system-x86 \
            qemu-utils \
            unzip \
            curl

      - name: Setup Packer
        uses: hashicorp/setup-packer@v3
        with:
          version: "1.15.1"

      - name: Verify Packer
        run: packer version

      - name: Packer init
        working-directory: packer
        run: packer init .

      - name: Packer validate
        working-directory: packer
        run: |
          packer validate \
            -var "iso_url=https://releases.ubuntu.com/noble/ubuntu-24.04.4-live-server-amd64.iso" \
            -var "iso_checksum=sha256:e907d92eeec9df64163a7e454cbc8d7755e8ddc7ed42f99dbc80c40f1a138433" \
            .
      
      - name: Packer build
        working-directory: packer
        env:
          PACKER_LOG: "1"
          PACKER_LOG_PATH: "packer.log"
        run: |
          packer build -on-error=abort \
            -var "iso_url=https://releases.ubuntu.com/noble/ubuntu-24.04.4-live-server-amd64.iso" \
            -var "iso_checksum=sha256:e907d92eeec9df64163a7e454cbc8d7755e8ddc7ed42f99dbc80c40f1a138433" \
            .

      - name: Validate build outputs
        if: always()
        working-directory: packer
        run: bash scripts/validate.sh

      - name: Show Packer log tail
        if: always()
        working-directory: packer
        run: |
          echo "==== Last 200 lines of packer.log ===="
          tail -n 200 packer.log || true

      - name: Upload baked image artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: baked-server-image
          path: |
            packer/output/**
            packer/*.manifest.json
            packer/packer.log
          retention-days: 14
